### ISSUE TITLE
Provide android builds

### ISSUE THREAD

**Issue by farzana840** [Playboy-Player/Playboy#2]
Hello please add support for Android. This is a very good app

**Comment by farzana840** [comment]
翻译：我将非常感谢您发布 Android 版本。谢谢

**Comment by YuiHrsw** [comment]
😊We are glad you enjoyed this project. The support for android is coming soon.

Due to the different operation logic between mobile and desktop, porting to Android platform requires some interface redesign. We plan to start adapting the UI to the android platform and provide multi-language support after completing the current playlists and search features. The android version is expected to be available at the end of the preview phase.

**Comment by farzana840** [comment]
早点等待下一个版本！感谢你杰出的工作 :)

**Comment by onnesoom** [comment]
>The Android version is expected to be available at the end of the preview phase.

i am really excited for he android version , the ui looks so promising .

**Comment by farzana840** [comment]
开发人员，Android 版本有任何更新吗？

**Comment by YuiHrsw** [comment]
我做了一些修改, 现在安卓端理论上也可以正常运行, 但是许多页面的响应式布局还没做好, 目前只有平板设备才能有比较正常的体验.
抱歉, 由于精力有限, 这个项目最近的开发进度会比较缓慢.

**Comment by farzana840** [comment]
我打算在平板电脑上使用该应用，而不是在手机上。如果它在平板电脑上运行良好，我将不胜感激，如果您能发布 Android 平板电脑版本

**Comment by YuiHrsw** [comment]
现在使用了 GitHub Actions 编译安卓版本, 可以从 [Actions](https://github.com/Playboy-Player/Playboy/actions) 下载测试, 界面和应用图标会在后续版本完善.

许多功能目前还未实现, 仅保留了 UI 入口.
视频播放由于没有实机, 没有测试过.

**Comment by farzana840** [comment]
好的，我测试了 Android 版本。它......可以播放视频，这很好。但它需要更多的工作和完善。我期待下一个 Android 版本。 在下次更新之前，我只会使用此版本。开发人员干得好。这是我用过的最好的视频播放器👍

**Comment by YuiHrsw** [comment]
This issue will be closed, for bug reports and feature requests, please open a new issue.
